# Generated by Django 5.2.12 on 2026-03-17 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('volatility', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeFeeDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Commission amount in USDC', max_digits=20)),
                ('level', models.IntegerField(help_text='Referral level (1-7)')),
                ('node_fee_total', models.DecimalField(decimal_places=2, help_text='Total 10% node fee from the purchase', max_digits=20)),
                ('commission_percentage', models.DecimalField(decimal_places=2, help_text='Percentage of node fee received (e.g., 100, 20, 10, etc.)', max_digits=5)),
                ('distributed_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(help_text='The user who made the purchase', on_delete=django.db.models.deletion.CASCADE, related_name='fees_paid', to=settings.AUTH_USER_MODEL)),
                ('purchase', models.ForeignKey(help_text='The volatility token purchase that generated this commission', on_delete=django.db.models.deletion.CASCADE, to='volatility.volatilityorder')),
                ('to_user', models.ForeignKey(help_text='The referrer receiving commission', on_delete=django.db.models.deletion.CASCADE, related_name='fees_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Node Fee Distribution',
                'verbose_name_plural': 'Node Fee Distributions',
                'ordering': ['-distributed_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(max_length=20)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('converted_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_from_link', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_1', models.JSONField(default=list)),
                ('level_2', models.JSONField(default=list)),
                ('level_3', models.JSONField(default=list)),
                ('level_4', models.JSONField(default=list)),
                ('level_5', models.JSONField(default=list)),
                ('level_6', models.JSONField(default=list)),
                ('level_7', models.JSONField(default=list)),
                ('referral_code', models.CharField(max_length=20, unique=True)),
                ('total_earned', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downlines', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_node', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral Node',
                'verbose_name_plural': 'Referral Nodes',
            },
        ),
        migrations.CreateModel(
            name='ReferralStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_referrals', models.IntegerField(default=0)),
                ('active_referrals', models.IntegerField(default=0, help_text='Referrals who have made at least one purchase')),
                ('total_earned', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('pending_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('level_1_count', models.IntegerField(default=0)),
                ('level_2_count', models.IntegerField(default=0)),
                ('level_3_count', models.IntegerField(default=0)),
                ('level_4_count', models.IntegerField(default=0)),
                ('level_5_count', models.IntegerField(default=0)),
                ('level_6_count', models.IntegerField(default=0)),
                ('level_7_count', models.IntegerField(default=0)),
                ('level_1_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('level_2_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('level_3_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('level_4_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('level_5_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('level_6_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('level_7_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral Statistics',
                'verbose_name_plural': 'Referral Statistics',
            },
        ),
    ]
