# Generated by Django 5.2.12 on 2026-03-17 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VolatilityToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_id', models.CharField(max_length=50, unique=True)),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('token_symbol', models.CharField(max_length=20)),
                ('current_price', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('monthly_yield_min', models.DecimalField(decimal_places=2, default=8.0, max_digits=5)),
                ('monthly_yield_max', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Volatility Token',
                'verbose_name_plural': 'Volatility Tokens',
            },
        ),
        migrations.CreateModel(
            name='VolatilityOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('total', models.DecimalField(decimal_places=8, max_digits=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volatility_orders', to=settings.AUTH_USER_MODEL)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volatility.volatilitytoken')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserVolatilityToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('yield_earned_total', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('last_yield_calculation', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volatility_tokens', to=settings.AUTH_USER_MODEL)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volatility.volatilitytoken')),
            ],
            options={
                'unique_together': {('user', 'token')},
            },
        ),
        migrations.CreateModel(
            name='YieldDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('distributed_at', models.DateTimeField(auto_now_add=True)),
                ('user_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yield_distributions', to='volatility.uservolatilitytoken')),
            ],
            options={
                'ordering': ['-distributed_at'],
            },
        ),
    ]
