# Generated by Django 5.2.12 on 2026-03-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volatility', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yielddistribution',
            name='token_price',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='yielddistribution',
            name='usd_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
