# Generated by Django 5.2.12 on 2026-03-18 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volatility', '0002_add_yield_usd_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='YieldSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_month', models.IntegerField()),
                ('expected_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('distributed_amount', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Distributed'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yield_schedules', to='volatility.uservolatilitytoken')),
            ],
            options={
                'ordering': ['day_of_month'],
                'unique_together': {('user_token', 'day_of_month')},
            },
        ),
        migrations.CreateModel(
            name='HourlyYield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_of_day', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('usd_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('token_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('distributed_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('user_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_yields', to='volatility.uservolatilitytoken')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_distributions', to='volatility.yieldschedule')),
            ],
            options={
                'ordering': ['-distributed_at'],
            },
        ),
    ]
