# Generated by Django 5.2.12 on 2026-03-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volatility', '0003_yieldschedule_hourlyyield'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservolatilitytoken',
            name='vol_yield',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
    ]
