# Generated by Django 5.2.12 on 2026-03-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volatility', '0004_uservolatilitytoken_vol_yield'),
    ]

    operations = [
        migrations.AddField(
            model_name='volatilityorder',
            name='node_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='10% node fee deducted from purchase', max_digits=20),
        ),
    ]
