# Generated by Django 5.2.12 on 2026-03-17 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BTCVolatilityWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vindex_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('vindex_purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('vindex_current_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('vol_yield', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_yield_earned', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('last_yield_credit', models.DateTimeField(blank=True, null=True)),
                ('today_yield_count', models.IntegerField(default=0)),
                ('yield_reset_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btc_volatility', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GrandBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_usdc', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_deposited', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grand_balance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='YieldCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('transaction_hash', models.CharField(max_length=66, unique=True)),
                ('credited_at', models.DateTimeField(auto_now_add=True)),
                ('day_of_year', models.IntegerField()),
                ('credit_number', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yield_credits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-credited_at'],
                'indexes': [models.Index(fields=['user', '-credited_at'], name='wallet_yiel_user_id_113df2_idx')],
            },
        ),
    ]
