# Generated by Django 5.2.12 on 2026-03-18 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='USDCSolanaWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(max_length=100, unique=True)),
                ('encrypted_private_key', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usdc_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'USDC Solana Wallet',
                'verbose_name_plural': 'USDC Solana Wallets',
            },
        ),
    ]
