# Generated by Django 5.2.12 on 2026-03-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_usdcsolanawallet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usdcsolanawallet',
            options={},
        ),
        migrations.RenameField(
            model_name='usdcsolanawallet',
            old_name='last_used',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='usdcsolanawallet',
            name='public_key',
            field=models.CharField(max_length=44, unique=True),
        ),
    ]
