# Generated by Django 5.2.12 on 2026-03-22 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycverification',
            name='id_back',
        ),
        migrations.RemoveField(
            model_name='kycverification',
            name='id_front',
        ),
        migrations.RemoveField(
            model_name='kycverification',
            name='proof_of_address',
        ),
        migrations.RemoveField(
            model_name='kycverification',
            name='selfie',
        ),
    ]
