# Generated by Django 5.2.12 on 2026-03-17 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('XRP', 'XRP'), ('BNB', 'BNB'), ('SOL', 'Solana'), ('TRX', 'TRON'), ('DOGE', 'Dogecoin'), ('ADA', 'Cardano'), ('LINK', 'Chainlink'), ('XLM', 'Stellar'), ('SUI', 'Sui'), ('TON', 'Toncoin'), ('SHIB', 'Shiba Inu'), ('DOT', 'Polkadot'), ('AAVE', 'Aave'), ('NEAR', 'Near'), ('PEPE', 'Pepe'), ('RENDER', 'Render'), ('ALGO', 'Algorand'), ('FIL', 'Filecoin')], max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_price_usd', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('market_cap_usd', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('volume_24h', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('price_change_24h', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_change_7d', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_change_30d', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fadakka_index_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('buy_at_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('ema_history', models.JSONField(default=dict)),
                ('last_price_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='IndexAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('payment_tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index_tracker.coin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'coin')},
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('open_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('high_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('low_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('close_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=30)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='index_tracker.coin')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['coin', '-timestamp'], name='index_track_coin_id_d1393b_idx')],
            },
        ),
    ]
